// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aereoliniafinal.Models;

namespace aereoliniafinal.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aereoliniafinal.Models.Aviones", b =>
                {
                    b.Property<int>("AvionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AvionesID");

                    b.ToTable("Aviones");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Ciudades", b =>
                {
                    b.Property<int>("CiudadesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.HasKey("CiudadesID");

                    b.HasIndex("PaisID");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.Property<int>("TipoSexoID")
                        .HasColumnType("int");

                    b.HasKey("ClienteID");

                    b.HasIndex("PaisID");

                    b.HasIndex("TipoSexoID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Empleados", b =>
                {
                    b.Property<int>("EmpleadosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEmpleadoID")
                        .HasColumnType("int");

                    b.HasKey("EmpleadosID");

                    b.HasIndex("TipoEmpleadoID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Pais", b =>
                {
                    b.Property<int>("PaisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisID");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("aereoliniafinal.Models.TipoEmpleado", b =>
                {
                    b.Property<int>("TipoEmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEmpleadoID");

                    b.ToTable("TipoEmpleado");
                });

            modelBuilder.Entity("aereoliniafinal.Models.TipoSexo", b =>
                {
                    b.Property<int>("TipoSexoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoSexoID");

                    b.ToTable("TipoSexo");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Vuelos", b =>
                {
                    b.Property<int>("VuelosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvionesID")
                        .HasColumnType("int");

                    b.Property<int>("CiudadesID")
                        .HasColumnType("int");

                    b.Property<string>("FechaLlegada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaSalida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VuelosID");

                    b.HasIndex("AvionesID");

                    b.HasIndex("CiudadesID");

                    b.ToTable("Vuelos");
                });

            modelBuilder.Entity("aereoliniafinal.Models.Ciudades", b =>
                {
                    b.HasOne("aereoliniafinal.Models.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aereoliniafinal.Models.Cliente", b =>
                {
                    b.HasOne("aereoliniafinal.Models.Pais", "Pais")
                        .WithMany("Cliente")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aereoliniafinal.Models.TipoSexo", "TipoSexo")
                        .WithMany("Cliente")
                        .HasForeignKey("TipoSexoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aereoliniafinal.Models.Empleados", b =>
                {
                    b.HasOne("aereoliniafinal.Models.TipoEmpleado", "TipoEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("TipoEmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aereoliniafinal.Models.Vuelos", b =>
                {
                    b.HasOne("aereoliniafinal.Models.Aviones", "Aviones")
                        .WithMany("Vuelos")
                        .HasForeignKey("AvionesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aereoliniafinal.Models.Ciudades", "Ciudades")
                        .WithMany("Vuelos")
                        .HasForeignKey("CiudadesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
